<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>FIML</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="version1_files/libs/clipboard/clipboard.min.js"></script>
<script src="version1_files/libs/quarto-html/quarto.js"></script>
<script src="version1_files/libs/quarto-html/popper.min.js"></script>
<script src="version1_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="version1_files/libs/quarto-html/anchor.min.js"></script>
<link href="version1_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="version1_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="version1_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="version1_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="version1_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">FIML</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="exam---introduction-to-modelling" class="level2">
<h2 class="anchored" data-anchor-id="exam---introduction-to-modelling">Exam - Introduction to Modelling</h2>
<p><strong><em>by Anita Munar (1652126)</em></strong></p>
<p>In this document, I present my code for the statistical model that is capable of predicting the amount customers will spend in a given webshop, after looking at their online behavior and personal characteristics.</p>
<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<p>First, I will load the libraries that I might need. Usually I load in all the libraries that might be useful for statistical modelling, in this case I left out the ‘wordcloud’ libraries, since the data I want to predict (spending amount) is integer, or possibly float, but not string or character data. The main objective here is that I load libraries such as ‘caret’, ‘tidyverse’ and ‘dplyr’ that are useful for executing basic statistical analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(class)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lattice</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lattice)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2
──</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>✔ tibble  3.1.8     ✔ dplyr   1.1.0
✔ tidyr   1.3.0     ✔ stringr 1.5.0
✔ readr   2.1.4     ✔ forcats 1.0.0
✔ purrr   1.0.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
✖ purrr::lift()   masks caret::lift()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: NLP

Attaching package: 'NLP'

The following object is masked from 'package:ggplot2':

    annotate</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(slam)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(e1071)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ISLR)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'magrittr'

The following object is masked from 'package:purrr':

    set_names

The following object is masked from 'package:tidyr':

    extract</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(naivebayes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>naivebayes 0.9.7 loaded</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fastDummies)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(missForest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'missForest' was built under R version 4.2.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mice)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'mice' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'mice'

The following object is masked from 'package:stats':

    filter

The following objects are masked from 'package:base':

    cbind, rbind</code></pre>
</div>
</div>
<p>Once I loaded the libraries, I will start loading in my csv data. I used my own public Github repository as a source to load in the csv file from.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>rawDF <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://raw.githubusercontent.com/HAN-M3DM-Data-Mining/data-mining-s2y2223-AnitaMunar/master/1652126webshop.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 1890 Columns: 10
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Find_website, Device
dbl (8): Purchase_Amount, Time_Spent_on_Website, Number_of_products_browsed,...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(rawDF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 10
  Purchas…¹ Time_…² Numbe…³ Pictu…⁴ Shipp…⁵ Revie…⁶ Find_…⁷ Ease_…⁸   Age Device
      &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; 
1      544.     914      22     3.9    2.07     4.5 Social…       4    23 Mobile
2      576.     644      13     3.7    2.59     4.8 Search…       4    37 PC    
3      702.     913      24     3      3.32     4.7 Search…       4    37 PC    
4      619.    1046      25     4.2    2.51     3.6 Search…       4    36 PC    
5      705.    1147      25     2.9    2.36     4.1 Search…       5    53 PC    
6      639.     849      21     2      4.27     4.9 Friend…       3    47 Mobile
# … with abbreviated variable names ¹​Purchase_Amount, ²​Time_Spent_on_Website,
#   ³​Number_of_products_browsed, ⁴​Pictures, ⁵​Shipping_Time, ⁶​Review_rating,
#   ⁷​Find_website, ⁸​Ease_of_purchase</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(rawDF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [1,890 × 10] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ Purchase_Amount           : num [1:1890] 544 576 702 619 705 ...
 $ Time_Spent_on_Website     : num [1:1890] 914 644 913 1046 1147 ...
 $ Number_of_products_browsed: num [1:1890] 22 13 24 25 25 21 27 22 15 25 ...
 $ Pictures                  : num [1:1890] 3.9 3.7 3 4.2 2.9 2 3.9 3.3 1.8 1.3 ...
 $ Shipping_Time             : num [1:1890] 2.07 2.59 3.32 2.51 2.36 4.27 4.84 4.05 2.01 3.74 ...
 $ Review_rating             : num [1:1890] 4.5 4.8 4.7 3.6 4.1 4.9 3.7 4.9 3.8 4.7 ...
 $ Find_website              : chr [1:1890] "Social_Media_Advertisement" "Search_Engine" "Search_Engine" "Search_Engine" ...
 $ Ease_of_purchase          : num [1:1890] 4 4 4 4 5 3 5 4 NA 4 ...
 $ Age                       : num [1:1890] 23 37 37 36 53 47 46 61 42 53 ...
 $ Device                    : chr [1:1890] "Mobile" "PC" "PC" "PC" ...
 - attr(*, "spec")=
  .. cols(
  ..   Purchase_Amount = col_double(),
  ..   Time_Spent_on_Website = col_double(),
  ..   Number_of_products_browsed = col_double(),
  ..   Pictures = col_double(),
  ..   Shipping_Time = col_double(),
  ..   Review_rating = col_double(),
  ..   Find_website = col_character(),
  ..   Ease_of_purchase = col_double(),
  ..   Age = col_double(),
  ..   Device = col_character()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
</div>
<p>First I load the data in and do initial inspections. After making sure that it is the correct dataset by checking the layout, I name it “webshop_data” for clarity and I am able to proceed to the tasks. At this unmodified state, the dataset has <strong>1890</strong> observations on 10 variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>webshop_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://raw.githubusercontent.com/HAN-M3DM-Data-Mining/data-mining-s2y2223-AnitaMunar/master/1652126webshop.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 1890 Columns: 10
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): Find_website, Device
dbl (8): Purchase_Amount, Time_Spent_on_Website, Number_of_products_browsed,...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p>Now for first inspections of the data: There are 2 columns with character data, and 8 columns consisting of ‘dbl’ data as for double, which is numeric data that holds values with decimal points and integers as well.</p>
<ol type="1">
<li><p>The first column, containing <strong>Purchase_Amount</strong>, is the <u>dependent variable</u>.</p></li>
<li><p>The second column, <strong>Time_Spent_on_Website</strong>, an <u>integer</u> data, is an independent variable that represents seconds.</p></li>
<li><p><strong>Number_of_products_browsed</strong>: <u>Integer</u> data on how many products were browsed through by the customer before their final payment.</p></li>
<li><p><strong>Pictures:</strong> The average number of pictures on the pages of the products bought by the customer. <u>Float</u> data, although pictures should be integer, but the point here was averaging, so we accept.</p></li>
<li><p><strong>Shipping_Time:</strong> The average number of days of shipping. <u>Float</u> data.</p></li>
<li><p><strong>Review_rating:</strong> The average rating on products bought by given customer a scale of 1-5. <u>Float.</u></p></li>
<li><p><strong>Find_website:</strong> <u>Character</u> data, based on 4 c choices that represent 3 given ways of finding and “Other” for customers that thought the first 3 option didn’t fit them.</p></li>
<li><p><strong>Ease of Purchase:</strong> <u>Integer</u> data on a scale of 1-5, where 1 represents worst and 5 the best rating from a customer survey.</p></li>
<li><p><strong>Age:</strong> The age of the customer, <u>integer</u> data.</p></li>
<li><p><strong>Device:</strong> <u>Character</u> data, with 2 choices being “Mobile” and “PC”.</p></li>
</ol>
<p>Now, lets get into the step-by-step breakdown of my tasks:</p>
</section>
<section id="part-1---preparing-the-data" class="level3">
<h3 class="anchored" data-anchor-id="part-1---preparing-the-data">Part 1 - Preparing the data</h3>
<p><strong>a.</strong> Remove rows with missing values</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>webshop_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(webshop_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>After running this code, I see now that webshop_data has only <strong>1556</strong> observations on 10 variables, and by scrolling through it I can make sure that rows with missing values were removed successfully.</p>
<p><strong>b.</strong> Run the model with all the independent variables, don’t forget to make dummy variable where appropriate. Are there outliers in the data? If so, report how you found out and explain how you dealt with this. Also explain the effect dealing with these outliers had on your model results.</p>
<p>(Editors note: the dummy variables and the explanation of model results will come later.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(webshop_data[,<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">8</span>,<span class="dv">9</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="version1_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Columns 2, 3, 4, 5, 6, 8, 9 are the columns with numeric data where I want to check outliers.</p>
<p>We see something quite alarming thanks to the boxplot: there are data for the Time_Spent_on_Website and Number_of_Products_Browsed columns, that goes under 0. This is impossible, since a person can not spend negative time on doing something, nor can they browse negative number of products. This data could have harsh effects on the regression model, possibly producing incorrect and unrealistic outcomes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>webshop_data <span class="ot">&lt;-</span> webshop_data[<span class="fu">rowSums</span>(webshop_data <span class="sc">&lt;</span> <span class="dv">0</span>) <span class="sc">==</span> <span class="dv">0</span>, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Using this command, we successfully deleted the negative values for the time spent variable. Now our dataset contains <strong>1521</strong> observations on 10 variables.</p>
<p>Now we can run the boxplot again, to see other outliers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(webshop_data[,<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">8</span>,<span class="dv">9</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="version1_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In later analysis, I have noticed that the following code does have a weird effect on column 8, Ease_of_Purchase, so I have left it out from the following code. This is most likely due to the fact that outliers from a scale of 1-5 are normal and should not be deleted, because all values will be exactly 4 once I include that column in the code. Although, other similarly scaled values such as Pictures and Shipping_Time are not as effected from this following cut, so I can leave those columns in the code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>webshop_data[,<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">9</span>)] <span class="ot">&lt;-</span> webshop_data[,<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">9</span>)] <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_if</span>(is.numeric, <span class="sc">~</span>{</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>    x <span class="ot">&lt;-</span> .x</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>    x[x <span class="sc">%in%</span> <span class="fu">boxplot.stats</span>(x)<span class="sc">$</span>out] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>    x</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  }) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This code replaces outliers with NA. Following, we delete these rows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>webshop_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(webshop_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This decreased the number of observations to <strong>1477</strong> from 1521, which is a realistic drop.</p>
<p><strong>Dummies</strong></p>
<p>We make dummy variables to represent categorical variables in a way that can be used in regression analysis. In a regression model, categorical variables cannot be included in their raw form, as they are not numerical. Instead, we create dummy variables that represent each category as a binary (0 or 1) variable. This allows us to include categorical variables in a regression model and examine their effect on the outcome variable.</p>
<p>Following, the Device dummy and Find_website dummy is added, and the original columns are removed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>webshop_data <span class="ot">&lt;-</span> webshop_data <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Device_dummy =</span> <span class="fu">recode</span>(Device, <span class="st">`</span><span class="at">Mobile</span><span class="st">`</span> <span class="ot">=</span> <span class="dv">1</span>, <span class="st">`</span><span class="at">PC</span><span class="st">`</span> <span class="ot">=</span> <span class="dv">2</span>),</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">Find_website_dummy =</span> <span class="fu">recode</span>(Find_website, </span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">`</span><span class="at">Social_Media_Advertisement</span><span class="st">`</span> <span class="ot">=</span> <span class="dv">1</span>, </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">`</span><span class="at">Search_Engine</span><span class="st">`</span> <span class="ot">=</span> <span class="dv">2</span>, </span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">`</span><span class="at">Friends_or_Family</span><span class="st">`</span> <span class="ot">=</span> <span class="dv">3</span>, </span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">`</span><span class="at">Other</span><span class="st">`</span> <span class="ot">=</span> <span class="dv">4</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Device, <span class="sc">-</span>Find_website)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>I will come back to the use the dummies in the regression model at the end.</p>
<p><strong>c.</strong> Check if there is multicollinearity between the independent variables. Show how you checked this and, if it causes problems, explain how you dealt with this.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(webshop_data[, <span class="fu">c</span>(<span class="st">"Time_Spent_on_Website"</span>, <span class="st">"Number_of_products_browsed"</span>,<span class="st">"Review_rating"</span>, <span class="st">"Ease_of_purchase"</span>, <span class="st">"Find_website_dummy"</span>, <span class="st">"Pictures"</span>, <span class="st">"Device_dummy"</span>)])</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cor_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                           Time_Spent_on_Website Number_of_products_browsed
Time_Spent_on_Website                1.000000000                0.976256859
Number_of_products_browsed           0.976256859                1.000000000
Review_rating                       -0.009549774               -0.007997318
Ease_of_purchase                    -0.043276455               -0.045389557
Find_website_dummy                   0.018945501                0.026297387
Pictures                             0.050069333                0.034594404
Device_dummy                        -0.002109302               -0.003675449
                           Review_rating Ease_of_purchase Find_website_dummy
Time_Spent_on_Website       -0.009549774     -0.043276455        0.018945501
Number_of_products_browsed  -0.007997318     -0.045389557        0.026297387
Review_rating                1.000000000      0.012298588        0.008889064
Ease_of_purchase             0.012298588      1.000000000        0.009915432
Find_website_dummy           0.008889064      0.009915432        1.000000000
Pictures                     0.019104529     -0.030958832        0.009394212
Device_dummy                 0.021485117      0.033034542       -0.019403143
                               Pictures Device_dummy
Time_Spent_on_Website       0.050069333 -0.002109302
Number_of_products_browsed  0.034594404 -0.003675449
Review_rating               0.019104529  0.021485117
Ease_of_purchase           -0.030958832  0.033034542
Find_website_dummy          0.009394212 -0.019403143
Pictures                    1.000000000  0.020770772
Device_dummy                0.020770772  1.000000000</code></pre>
</div>
</div>
<p>From this matrix I see that other than the perfect correlations between variables that are the same variable, being the value of 1, but I will ignore this.</p>
<p>On the dimension of Time_Spent_on_Website:</p>
<pre><code>Number_of_products_browsed           0.976256859</code></pre>
<p>This means a high correlation, but it is for obvious reasons: the more the customer spends on the website, the more products they are likely to browse. To reduce this multicollinearity is cruical for the model to achieve an optimal outcome.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>webshop_data<span class="sc">$</span>Time_Products_Average <span class="ot">&lt;-</span> (webshop_data<span class="sc">$</span>Time_Spent_on_Website<span class="sc">/</span><span class="dv">60</span> <span class="sc">+</span> webshop_data<span class="sc">$</span>Number_of_products_browsed)<span class="sc">/</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This code divides the Time_Spent_on_Website variable by 60 to convert the time from seconds to minutes, and then averages it with Number_of_products_browsed. The resulting variable represents the average time spent on the website per product browsed, in minutes.</p>
<p>There are 1477 observations on <strong>11</strong> variables currently in the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>webshop_data<span class="sc">$</span>Time_Spent_on_Website <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>webshop_data<span class="sc">$</span>Number_of_products_browsed <span class="ot">&lt;-</span> <span class="cn">NULL</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>After this command that removes the original two columns if time and products browsed, there are 1477 observations on <strong>9</strong> variables.</p>
<p><strong>d.</strong> Check if there are non-linear relationships between the independent variables and the dependent variables. If there are, make the appropriate transformations. Show and explain how you found out and how you know the transformation makes the model better.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot of Age vs. Purchase_Amount</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(webshop_data<span class="sc">$</span>Age, webshop_data<span class="sc">$</span>Purchase_Amount)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="version1_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot of Shipping_Time vs. Purchase_Amount</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(webshop_data<span class="sc">$</span>Shipping_Time, webshop_data<span class="sc">$</span>Purchase_Amount)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="version1_files/figure-html/unnamed-chunk-14-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot of Pictures vs. Purchase_Amount</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(webshop_data<span class="sc">$</span>Pictures, webshop_data<span class="sc">$</span>Purchase_Amount)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="version1_files/figure-html/unnamed-chunk-14-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The relationships of Shipping time and Pictures on the dimension of Purchase_Amount seem linear, but I can see a singificant non-linear relationship between Age and Purchase_Amount.</p>
<p><img src="images/image-407692895.png" class="img-fluid"></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(webshop_data, <span class="fu">aes</span>(<span class="at">x =</span> Find_website_dummy, <span class="at">y =</span> Purchase_Amount)) <span class="sc">+</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Find Website Dummy"</span>, <span class="at">y =</span> <span class="st">"Purchase Amount"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,
: pseudoinverse used at 0.985</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,
: neighborhood radius 1.015</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,
: reciprocal condition number 2.7213e-29</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,
: There are other near singularities as well. 1</code></pre>
</div>
<div class="cell-output-display">
<p><img src="version1_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(webshop_data, <span class="fu">aes</span>(<span class="at">x =</span> Device_dummy, <span class="at">y =</span> Purchase_Amount)) <span class="sc">+</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> <span class="fu">poly</span>(x, <span class="dv">2</span>), <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Computation failed in `stat_smooth()`
Caused by error in `poly()`:
! 'degree' must be less than number of unique points</code></pre>
</div>
<div class="cell-output-display">
<p><img src="version1_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>There seem to be no significant non-linear relationship in case of the two dummy variables.</p>
</section>
<section id="part-2---create-the-model" class="level3">
<h3 class="anchored" data-anchor-id="part-2---create-the-model">Part 2 - create the model</h3>
<p><strong>a.</strong> After the steps in part 1 are done, present the model in a table APA style. For each independent variable in the model, clearly explain what the output means in the context of the web shop.</p>
<p>Here I decided to not set my data into test and train data, since for simple linear regression models with one predictor it is also correct to use the whole dataset. I will evaluate on the performance of the model later.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Purchase_Amount<span class="sc">~</span>Time_Products_Average,<span class="at">data=</span>webshop_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Time_Products_Average, data = webshop_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-341.80  -31.29    9.16   43.18  176.40 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           384.2137     5.0900   75.48   &lt;2e-16 ***
Time_Products_Average  12.4034     0.2807   44.20   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 64.27 on 1475 degrees of freedom
Multiple R-squared:  0.5697,    Adjusted R-squared:  0.5695 
F-statistic:  1953 on 1 and 1475 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<pre><code>Multiple R-squared:  0.5862,    Adjusted R-squared:  0.5859 </code></pre>
<p>This is an R2 regression of 0.58, which is a quite good correlation. It hints that the purchased value is correlated with theaverage time spent on the website per product browsed, in minutes.</p>
<pre><code>Time_Products_Average  12.4034</code></pre>
<p>Also, when 1 more product is being looked at per minute, the Purchase Amount may increase by 12 euro.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Purchase_Amount<span class="sc">~</span>Pictures,<span class="at">data=</span>webshop_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Pictures, data = webshop_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-365.18  -61.74    4.18   67.81  267.89 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  590.520      8.747  67.509   &lt;2e-16 ***
Pictures       2.032      2.762   0.736    0.462    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 97.97 on 1475 degrees of freedom
Multiple R-squared:  0.000367,  Adjusted R-squared:  -0.0003107 
F-statistic: 0.5415 on 1 and 1475 DF,  p-value: 0.4619</code></pre>
</div>
</div>
<p>From the Coefficient - Estimate, we see that if a customer checked out 1 more picture of the product, the purchase amount would be increased by 2 euro. This signs a rather low correlation. The R squared values are also showing that this is not the close correlation we are looking for when looking for purchase values later. Therefore, the Picture variable is not as useful for influencing the purchase value outcome.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Purchase_Amount<span class="sc">~</span>Shipping_Time,<span class="at">data=</span>webshop_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Shipping_Time, data = webshop_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-367.83  -62.66    3.38   67.89  265.30 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   594.3373     8.4522   70.32   &lt;2e-16 ***
Shipping_Time   0.7794     2.6836    0.29    0.772    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 97.98 on 1475 degrees of freedom
Multiple R-squared:  5.718e-05, Adjusted R-squared:  -0.0006208 
F-statistic: 0.08434 on 1 and 1475 DF,  p-value: 0.7715</code></pre>
</div>
</div>
<p>We can see from these outcomes (coefficient estimate, R2 being 0.78, p-value being 0.77) that the Shipping time is not be the variable that will get us closer to a meaningful correlation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Purchase_Amount<span class="sc">~</span>Review_rating,<span class="at">data=</span>webshop_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Review_rating, data = webshop_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-384.46  -60.20    2.64   66.12  275.21 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    456.866     21.366  21.382  &lt; 2e-16 ***
Review_rating   35.023      5.315   6.589 6.14e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 96.58 on 1475 degrees of freedom
Multiple R-squared:  0.02859,   Adjusted R-squared:  0.02794 
F-statistic: 43.42 on 1 and 1475 DF,  p-value: 6.135e-11</code></pre>
</div>
</div>
<p>From this we can see that there is small correlation between the Review rating and the Purchase amount. The R2 is around 0.02, which is very low. From the Estimate we can conclude that if the Review rating goes up by 1, the Purchase value would go up by 35 euro. Even though this shows that a higher rating will result in more income for the webshop, due to the low R2, we can not determine close and meaningful correlation in this variable and the independent variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Purchase_Amount<span class="sc">~</span>Ease_of_purchase,<span class="at">data=</span>webshop_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Ease_of_purchase, data = webshop_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-366.67  -62.63    3.50   67.75  264.98 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      593.9626    18.0032  32.992   &lt;2e-16 ***
Ease_of_purchase   0.6785     4.4539   0.152    0.879    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 97.99 on 1475 degrees of freedom
Multiple R-squared:  1.573e-05, Adjusted R-squared:  -0.0006622 
F-statistic: 0.02321 on 1 and 1475 DF,  p-value: 0.8789</code></pre>
</div>
</div>
<p>Same as earlier with the Shipping time. The R2 is very low. The Estimate is 0.6, meaning that if an Ease of purchase rating goes up by 1, the Purchase amount increases by 0.6 euro. This is too low to be considered significant. Same with p-value, 0.88.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Purchase_Amount<span class="sc">~</span>Age,<span class="at">data=</span>webshop_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Age, data = webshop_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-341.41  -62.91    3.45   68.58  262.27 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 647.4942    12.2606  52.811  &lt; 2e-16 ***
Age          -1.1188     0.2641  -4.236 2.41e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 97.4 on 1475 degrees of freedom
Multiple R-squared:  0.01202,   Adjusted R-squared:  0.01135 
F-statistic: 17.95 on 1 and 1475 DF,  p-value: 2.414e-05</code></pre>
</div>
</div>
<p>Here we can not determine close correlation either. The R2 is 0.01 and the Estimate is -1.1. The estimate being negative could sign for an inverse correlation - meaning that the younger the customer, the more they might spend. Although the amount is only around 1 euros, so it is not significant. I keep it in mind that the Age variable is non-linear, therefore later on I will run a different model on this variable.</p>
<p>Next, we check which one of the dummies has an effect on the Purchase_Amount.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Purchase_Amount<span class="sc">~</span>Device_dummy,<span class="at">data=</span>webshop_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Device_dummy, data = webshop_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-362.84  -62.12    3.78   68.17  263.48 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   587.510     10.065  58.370   &lt;2e-16 ***
Device_dummy    5.335      5.667   0.942    0.347    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 97.96 on 1475 degrees of freedom
Multiple R-squared:  0.0006006, Adjusted R-squared:  -7.692e-05 
F-statistic: 0.8865 on 1 and 1475 DF,  p-value: 0.3466</code></pre>
</div>
</div>
<p>The Estimate coefficient, the R2 and the p-value for Device:</p>
<pre><code>Device_dummy    5.335 

Multiple R-squared:  0.0006006

p-value: 0.3466</code></pre>
<p>From these values we can tell that the Device type does not have a high significant effect on the Purchase Amount, there is only a 5 euro difference between using PC or using Mobile.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Purchase_Amount<span class="sc">~</span>Find_website_dummy,<span class="at">data=</span>webshop_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Find_website_dummy, data = webshop_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-366.25  -62.20    3.82   68.46  263.66 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         599.727      7.329  81.834   &lt;2e-16 ***
Find_website_dummy   -1.732      3.902  -0.444    0.657    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 97.98 on 1475 degrees of freedom
Multiple R-squared:  0.0001335, Adjusted R-squared:  -0.0005443 
F-statistic: 0.197 on 1 and 1475 DF,  p-value: 0.6572</code></pre>
</div>
</div>
<pre><code>Find_website_dummy   -1.732

Multiple R-squared:  0.0001335

p-value: 0.6572</code></pre>
<p>We can also determine that the different routes from which the customers found the website did not have a statistically significant effect on the Purchase Amount.</p>
<p><strong>Takeaways from simple regression</strong><br>
To sum up the results of simple regressions, we see that the most significant variables are</p>
<p>-Time_Products_Average<br>
-Review_rating<br>
-possibly Device_dummy</p>
<p>Now, lets look at the multiple regression!</p>
<p><em>Multiple regression with all off the independent variables:</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>model_a <span class="ot">&lt;-</span> <span class="fu">lm</span>(Purchase_Amount <span class="sc">~</span> Time_Products_Average<span class="sc">+</span>Review_rating<span class="sc">+</span>Ease_of_purchase<span class="sc">+</span>Pictures<span class="sc">+</span>Find_website_dummy<span class="sc">+</span>Shipping_Time<span class="sc">+</span>Device_dummy, <span class="at">data =</span> webshop_data)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Time_Products_Average + Review_rating + 
    Ease_of_purchase + Pictures + Find_website_dummy + Shipping_Time + 
    Device_dummy, data = webshop_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-330.87  -29.61    9.19   40.76  151.76 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           221.0071    20.8700  10.590   &lt;2e-16 ***
Time_Products_Average  12.4797     0.2706  46.120   &lt;2e-16 ***
Review_rating          36.3016     3.4046  10.663   &lt;2e-16 ***
Ease_of_purchase        5.9879     2.8162   2.126   0.0336 *  
Pictures               -1.5540     1.7459  -0.890   0.3736    
Find_website_dummy     -4.5714     2.4637  -1.855   0.0637 .  
Shipping_Time          -0.7446     1.6946  -0.439   0.6604    
Device_dummy            4.6674     3.5814   1.303   0.1927    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 61.82 on 1469 degrees of freedom
Multiple R-squared:  0.6036,    Adjusted R-squared:  0.6017 
F-statistic: 319.5 on 7 and 1469 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<pre><code>Multiple R-squared:  0.6036,    Adjusted R-squared:  0.6017  </code></pre>
<p>Model_a shows the regression for each linear independent variable before standardizing. The on-linear variable, Age, will be reflected on in a different model.<br>
<br>
An R-squared value of 0.6 indicates that 60% of the variation in the dependent variable (Purchase_Amount) can be explained by the independent variables (Time_Products_Average, Review_rating, Ease_of_purchase, Pictures, Find_website_dummy, Shipping_Time, Device_dummy) in the model. In other words, the model explains a moderate amount of the variability in the data.</p>
<p>In this layout I also see slightly different outcomes for the Coefficients Estimate aspect.</p>
<pre><code>Time_Products_Average  12.4797</code></pre>
<p>This confirms our earlier suspicion that the products looked at per minute has a high correlation with the Purchase_Amount. What I also see better with this form of regression is that the Review_rating is more correlated with the Purchase_Amount.</p>
<pre><code>Review_rating          36.3016</code></pre>
<p>This confirms our previous finding that the Review rating has a very high correlation with the Purchase amount: if the rating goes up by 1, the purchased amount goes up by 35 euro.</p>
<pre><code>Ease_of_purchase        5.9879</code></pre>
<p>Also, the Ease of purchase rating shows that if the ease is perceived 1 score higher, the purchase amount goes up by 6 euro.</p>
<pre><code>Device_dummy            4.6674</code></pre>
<p>Similarly for the type of Device, the multiple regression shows a higher significance on the Purchase Amount. Meaning that people shopping from their PC increases the estimated purchase amount by 4 euro on average.</p>
<pre><code>Find_website_dummy     -4.5714</code></pre>
<p>Lastly, the Find_website dummy, showing a stronger influence than in individual regression earlier. The order in which I wrote the code is the following:<br>
“Social_Media_Advertisement” = 1,<br>
“Search_Engine” = 2,<br>
“Friends_or_Family” = 3,<br>
“Other” = 4))<br>
Meaning, that the change between ways of reaching the website could have an effect on the purchase. If the rank increased by 1, there is a chance that the person spends 3 euro less. Therefore, customers approaching the website from social media and search engine generate slightly higher revenue than those who find it through friend and family or other methods.</p>
<p>These outcomes put the individual simple regressions into a different light.</p>
<p><strong>Takeaways from multiple regression</strong><br>
-Review_rating<br>
-Time_Products_Average<br>
-Ease_of_purchase<br>
-Device<br>
-Find_website</p>
<p>These 5 variables have been found to have an effect on the Purchase_Amount outcomes. Therefore, I will proceed with this information in mind.</p>
<pre><code>Shipping_Time          -0.7395

Pictures               -1.5540</code></pre>
<p>These variables have a weak relationship with the target variable Purchase_Amount. However, it is still useful to keep them in the model because they might have some predictive value when used in combination with other variables. I tried deleting them, but it does not make the model more accurate.</p>
<p>Also, I will not delete the “Age” variable, since I seen earlier that there is a non-linear relationship between Age and Purchase_Amount. I will get back to this soon. This last code successfully removed the variables that I deemed no longer significant.<br>
My dataset currently consists of 1477 observations on <strong>7</strong> variables.</p>
<p><strong>b</strong>.Create a model in which the appropriate variables are standardized and present the results next to the model of part 2a. Note that standardization does not work for non-linear effects. Based on this model, which of the standardized variables has the largest effect on how the customers spend on average?</p>
<p>After I cleaned the data, we can start preparing to test regressions and build a new standardized model. I will add the variables: “Time_Products_Average”, “Review_rating” and “Ease_of_purchase”, because I seen from the model that these have a higher significance on the the purchase amount. I left out the dummies, because scaling them may not be necessary as they are already in a binary form and may affect their interpretation. Coefficients of these variables will be interpreted as the effect of a one-standard-deviation increase in device or finding website route, which does not make sense. Therefore, I will keep the dummies separate from the continous variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>scaled_data <span class="ot">&lt;-</span> webshop_data</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>scaled_data[, <span class="fu">c</span>(<span class="st">"Time_Products_Average"</span>, <span class="st">"Review_rating"</span>, <span class="st">"Ease_of_purchase"</span>)] <span class="ot">&lt;-</span> <span class="fu">scale</span>(scaled_data[, <span class="fu">c</span>(<span class="st">"Time_Products_Average"</span>, <span class="st">"Review_rating"</span>, <span class="st">"Ease_of_purchase"</span>)])</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>model_b <span class="ot">&lt;-</span> <span class="fu">lm</span>(Purchase_Amount <span class="sc">~</span> Time_Products_Average<span class="sc">+</span>Review_rating<span class="sc">+</span>Ease_of_purchase<span class="sc">+</span>Find_website_dummy<span class="sc">+</span>Device_dummy, <span class="at">data =</span> scaled_data)</span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Time_Products_Average + Review_rating + 
    Ease_of_purchase + Find_website_dummy + Device_dummy, data = scaled_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-331.47  -29.85    9.25   40.76  147.72 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            596.837      7.763  76.885   &lt;2e-16 ***
Time_Products_Average   74.318      1.611  46.140   &lt;2e-16 ***
Review_rating           17.149      1.609  10.657   &lt;2e-16 ***
Ease_of_purchase         3.466      1.611   2.151   0.0316 *  
Find_website_dummy      -4.612      2.462  -1.873   0.0613 .  
Device_dummy             4.634      3.578   1.295   0.1955    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 61.8 on 1471 degrees of freedom
Multiple R-squared:  0.6033,    Adjusted R-squared:  0.602 
F-statistic: 447.4 on 5 and 1471 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We can see that scaling the data did not improve the R2 value by any amount.</p>
<pre><code>Multiple R-squared:  0.6035,    Adjusted R-squared:  0.6019</code></pre>
<p>The R-squared value of 0.6033 indicates that approximately 60.33% of the variability in the purchase amount can be explained by the variables included in the model.</p>
<pre><code>Coefficients:
                      Estimate   Std.Error  t value
Time_Products_Average   74.375      1.612  46.135</code></pre>
<p>The variable with the largest absolute t-value has the largest effect on the response variable. This is the Time_Products_Average.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare the models</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Time_Products_Average + Review_rating + 
    Ease_of_purchase + Pictures + Find_website_dummy + Shipping_Time + 
    Device_dummy, data = webshop_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-330.87  -29.61    9.19   40.76  151.76 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           221.0071    20.8700  10.590   &lt;2e-16 ***
Time_Products_Average  12.4797     0.2706  46.120   &lt;2e-16 ***
Review_rating          36.3016     3.4046  10.663   &lt;2e-16 ***
Ease_of_purchase        5.9879     2.8162   2.126   0.0336 *  
Pictures               -1.5540     1.7459  -0.890   0.3736    
Find_website_dummy     -4.5714     2.4637  -1.855   0.0637 .  
Shipping_Time          -0.7446     1.6946  -0.439   0.6604    
Device_dummy            4.6674     3.5814   1.303   0.1927    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 61.82 on 1469 degrees of freedom
Multiple R-squared:  0.6036,    Adjusted R-squared:  0.6017 
F-statistic: 319.5 on 7 and 1469 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Time_Products_Average + Review_rating + 
    Ease_of_purchase + Find_website_dummy + Device_dummy, data = scaled_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-331.47  -29.85    9.25   40.76  147.72 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            596.837      7.763  76.885   &lt;2e-16 ***
Time_Products_Average   74.318      1.611  46.140   &lt;2e-16 ***
Review_rating           17.149      1.609  10.657   &lt;2e-16 ***
Ease_of_purchase         3.466      1.611   2.151   0.0316 *  
Find_website_dummy      -4.612      2.462  -1.873   0.0613 .  
Device_dummy             4.634      3.578   1.295   0.1955    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 61.8 on 1471 degrees of freedom
Multiple R-squared:  0.6033,    Adjusted R-squared:  0.602 
F-statistic: 447.4 on 5 and 1471 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<pre><code>&gt; summary(model_a)

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           221.0071    20.8700  10.590   &lt;2e-16 ***
Time_Products_Average  12.4797     0.2706  46.120   &lt;2e-16 ***
Review_rating          36.3016     3.4046  10.663   &lt;2e-16 ***
Ease_of_purchase        5.9879     2.8162   2.126   0.0336 *  
Pictures               -1.5540     1.7459  -0.890   0.3736    
Find_website_dummy     -4.5714     2.4637  -1.855   0.0637 .  
Shipping_Time          -0.7446     1.6946  -0.439   0.6604    
Device_dummy            4.6674     3.5814   1.303   0.1927    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 61.82 on 1469 degrees of freedom
Multiple R-squared:  0.6036,    Adjusted R-squared:  0.6017 
F-statistic: 319.5 on 7 and 1469 DF,  p-value: &lt; 2.2e-16

&gt; summary(model_b)

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            596.837      7.763  76.885   &lt;2e-16 ***
Time_Products_Average   74.318      1.611  46.140   &lt;2e-16 ***
Review_rating           17.149      1.609  10.657   &lt;2e-16 ***
Ease_of_purchase         3.466      1.611   2.151   0.0316 *  
Find_website_dummy      -4.612      2.462  -1.873   0.0613 .  
Device_dummy             4.634      3.578   1.295   0.1955    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 61.8 on 1471 degrees of freedom
Multiple R-squared:  0.6033,    Adjusted R-squared:  0.602 
F-statistic: 447.4 on 5 and 1471 DF,  p-value: &lt; 2.2e-1</code></pre>
<p>Looking at the summary output of the two models, we can see that they both have the same significant predictors: Time_Products_Average, Review_rating, Ease_of_purchase, Find_website_dummy, and Device_dummy. However, model_b does not include the predictor Pictures.</p>
<p>The adjusted R-squared value for model_a is 0.6017 and for model_b it is 0.602, indicating that both models explain approximately 60% of the variation in the response variable. The F-statistic is also higher for model_b than for model_a, indicating a better fit.</p>
<p>Although model_b has a higher R-squared and F-statistic, it has fewer predictors than model_a.</p>
<p>In order to separately deal with Age variable that was found to have a non-linear relationship with Purchase_Amount:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>model_age <span class="ot">&lt;-</span> <span class="fu">lm</span>(Purchase_Amount <span class="sc">~</span> Age <span class="sc">+</span> <span class="fu">I</span>(Age<span class="sc">^</span><span class="dv">2</span>), <span class="at">data =</span> webshop_data)</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Age + I(Age^2), data = webshop_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-238.121  -59.675   -1.132   58.551  231.111 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -182.80178   37.24972  -4.907 1.03e-06 ***
Age           37.03110    1.65769  22.339  &lt; 2e-16 ***
I(Age^2)      -0.41877    0.01803 -23.231  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 83.36 on 1474 degrees of freedom
Multiple R-squared:  0.2768,    Adjusted R-squared:  0.2758 
F-statistic: 282.1 on 2 and 1474 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>This model includes both the linear effect of age and the quadratic effect of age on purchase amount.<br>
</p>
<p><strong>c.</strong> Use the model to make a prediction about a new customer that is not in the data. Keep in mind the principle of parsimony when making the prediction. Also explain how you know that this model is suitable for making a prediction. The customer has the following characteristics:</p>
<p>Time_Products_Average = 12.05 Pictures = 3.4 Shipping_Time = 2.6 Review_rating&nbsp;= 4.5 Find_website_dummy = 3 Ease_of_purchase = 4 Age = 35 Device_dummy = 2</p>
<p>Remark:</p>
<blockquote class="blockquote">
<p>Time spent on website&nbsp;&nbsp; 723 seconds<br>
Total number of products browsed&nbsp;&nbsp;&nbsp; 20 products</p>
</blockquote>
<p>I remembered that I changed the above while normalizing, so I will input the following:</p>
<p>Time_Products_Average = (723/60 + 20)/2 = 12.05</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the linear regression model</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>model_c <span class="ot">&lt;-</span> <span class="fu">lm</span>(Purchase_Amount <span class="sc">~</span> Time_Products_Average <span class="sc">+</span> Review_rating <span class="sc">+</span> Ease_of_purchase, <span class="at">data =</span> webshop_data)</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Time_Products_Average + Review_rating + 
    Ease_of_purchase, data = webshop_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-331.24  -29.23    8.93   41.54  143.31 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           213.9735    18.3789  11.642   &lt;2e-16 ***
Time_Products_Average  12.4548     0.2704  46.055   &lt;2e-16 ***
Review_rating          36.2973     3.4054  10.659   &lt;2e-16 ***
Ease_of_purchase        6.1140     2.8152   2.172     0.03 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 61.87 on 1473 degrees of freedom
Multiple R-squared:  0.6019,    Adjusted R-squared:  0.6011 
F-statistic: 742.3 on 3 and 1473 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Based on the summary of the model_c, we can judge variables we want to include in our prediction.</p>
<p>I decided to keep the following variables after concluding that the dummies confuse the model and the shipping time plus the pictres do not have a high signficance: Time_Products_Average, Review_rating, Ease_of_purchase.</p>
<p>Now, I can make a prediction about a new customer’s purchase amount using the predict function in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>new_customer <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Time_Products_Average =</span> <span class="fl">12.05</span>, <span class="at">Review_rating =</span> <span class="fl">4.5</span>, <span class="at">Ease_of_purchase =</span> <span class="dv">4</span>)</span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>predicted_purchase_amount <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_c, <span class="at">newdata =</span> new_customer)</span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(predicted_purchase_amount)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
551.8471 </code></pre>
</div>
</div>
<p>Based on the most statistically significant variables, the new customer will be likely to spend around 551 euro in the webshop, based on their characteristics and behavior.<br>
To evaluate whether this prediction is correct, we would need to compare it to the actual purchase amount that the new customer makes. However, since the new customer data was not included in the training or test sets, we do not have access to their actual purchase amount to make this comparison.</p>
<p>One way to assess the accuracy of the model’s predictions is to use cross-validation or hold-out testing techniques to estimate the model’s performance on new data. If the model performs well on new data, it suggests that the model is generalizable and likely to make accurate predictions on new customers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the mean squared error (MSE) of the model using cross-validation</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>mse <span class="ot">&lt;-</span> <span class="fu">train</span>(Purchase_Amount <span class="sc">~</span> Time_Products_Average <span class="sc">+</span> Review_rating <span class="sc">+</span> Ease_of_purchase, <span class="at">data =</span> webshop_data, <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">trControl =</span> <span class="fu">trainControl</span>(<span class="st">"cv"</span>, <span class="dv">10</span>), <span class="at">metric =</span> <span class="st">"RMSE"</span>)</span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a><span class="co"># print the mean squared error</span></span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear Regression 

1477 samples
   3 predictor

No pre-processing
Resampling: Cross-Validated (10 fold) 
Summary of sample sizes: 1329, 1329, 1329, 1329, 1330, 1329, ... 
Resampling results:

  RMSE      Rsquared  MAE     
  61.88606  0.601645  46.03798

Tuning parameter 'intercept' was held constant at a value of TRUE</code></pre>
</div>
</div>
<p>The cross-validation results show that the model has an RMSE (Root Mean Squared Error) of 61.78, which indicates that on average, the model’s predictions are off by $61.78.<br>
The R-squared value is 0.60, which indicates that the model explains 60% of the variation in the target variable.<br>
The MAE (Mean Absolute Error) is 46.05, which is the average absolute difference between the predicted and actual purchase amount. Overall, the model seems to perform reasonably well, but it may not be perfect.<br>
<br>
The predicted value was 551 euro, and based on cross-validation, the new customer is expected to spend around 490-610 euro in the webshop.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co"># extract the residuals from the model</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>residuals <span class="ot">&lt;-</span> <span class="fu">resid</span>(model_c)</span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a><span class="co"># create a normal probability plot of the residuals</span></span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(residuals)</span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="version1_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            1             2             3             4             5 
 -89.19339871   15.14705681   48.71616532  -13.88819990   36.52642086 
            6             7             8             9            10 
  10.39535074   47.07772571  -21.65337575   35.91314670   13.16965888 
           11            12            13            14            15 
  26.76318873  -51.84314881  -38.04438303   13.05104287  -40.51801035 
           16            17            18            19            20 
  58.32939249 -103.00178205   51.26238783  -14.51453512   25.90722293 
           21            22            23            24            25 
-177.73799113   56.67607672    2.83921180   53.03918776 -129.67292411 
           26            27            28            29            30 
  35.63467426    0.85338011   42.92232434  -74.80827699  -51.33717994 
           31            32            33            34            35 
  -3.82645547   37.24917393   47.86654096   13.47463463   31.40598456 
           36            37            38            39            40 
 -38.72763281    7.59172723  117.63370418  -35.54962434  -29.43579753 
           41            42            43            44            45 
  25.52447144  -11.50199830    4.72972610   19.87488527    9.80645956 
           46            47            48            49            50 
   2.93103449  -78.44087613   28.00262512    8.75212383   19.11151282 
           51            52            53            54            55 
  -7.89048566   50.57214256   73.39176312  -24.23602529  -35.35955828 
           56            57            58            59            60 
   3.55178485   22.99566247  -92.39819335 -110.04712301   57.14745477 
           61            62            63            64            65 
  47.39899788   23.08654469   13.52734600  -42.01533636   39.73997027 
           66            67            68            69            70 
  64.07214623 -130.52649150   73.38154374   87.17877161   61.89870629 
           71            72            73            74            75 
  13.05237556  -26.50259863    6.07329640  -41.85983453  143.31059123 
           76            77            78            79            80 
 -97.72777571  -40.44997428   82.80865283  -43.90936185   16.26722558 
           81            82            83            84            85 
  -5.27196656    0.33329116   11.55360597  -12.92343243  -37.38675848 
           86            87            88            89            90 
 -45.96219855   31.69248686   -9.90641882   22.03138368  -28.97976077 
           91            92            93            94            95 
 -57.10543274   99.75981743  -18.98636884  -40.80712540   73.70259603 
           96            97            98            99           100 
-221.49301171   28.42566887    8.20885789  -36.44929496    6.46868300 
          101           102           103           104           105 
   3.71594553  -60.49048899   75.33303739   21.33999356   10.98364458 
          106           107           108           109           110 
 -24.35196813  -83.96531191   49.58819226  -27.38819336  -20.31326875 
          111           112           113           114           115 
 -20.38193572   69.62720352   40.26382800   27.04695546    2.29789313 
          116           117           118           119           120 
  -4.22023222  -17.74797139  -41.15198304  -84.56520633   -2.42185425 
          121           122           123           124           125 
 -22.93679793   19.25510036   -5.29264970   62.72016779   42.44548328 
          126           127           128           129           130 
 -89.16815283   23.46285287   -1.71998572  -35.55256233   27.01028234 
          131           132           133           134           135 
-226.92428093  -50.62325323   35.20884877   14.48437628   75.23384864 
          136           137           138           139           140 
  62.22277672  -50.98434332   15.39435879   -9.52283244  -14.51789531 
          141           142           143           144           145 
 -56.61443418  -48.03219507  -62.27139947  -27.20071526   81.49160184 
          146           147           148           149           150 
 -52.94247562   98.64041809   43.67854657 -184.84074352   -6.70785295 
          151           152           153           154           155 
  85.27848399   -5.74323600  -41.64077138   18.32753290    7.68373667 
          156           157           158           159           160 
-165.83430926  -51.87372584   23.88919001 -209.88955937   14.34699599 
          161           162           163           164           165 
  12.85674602   -9.87751396   11.82537545  -28.97907606   27.36601813 
          166           167           168           169           170 
  -2.84082226   55.03378699   30.60619217  -14.00751048   67.95679235 
          171           172           173           174           175 
-143.19378046  -36.17356762   43.71339585   -8.50672341  -35.78113100 
          176           177           178           179           180 
  -6.98689730   57.27816605   88.14056146    7.18241882   -6.16447552 
          181           182           183           184           185 
 -19.79555227 -137.01302050   54.49217532    9.79780145   15.88461739 
          186           187           188           189           190 
  50.43127022   67.82487567 -152.73037402   58.68622832  -46.09483201 
          191           192           193           194           195 
  81.88458184   -6.15072404   46.83082464   48.45151738   46.18604102 
          196           197           198           199           200 
 -45.37706682  -11.46545712   55.76001311   51.12064652   90.64468918 
          201           202           203           204           205 
  30.55268471   45.11181393   19.16145737   13.33438358 -196.30967781 
          206           207           208           209           210 
  69.40603040   -1.82338304   28.40664563   19.77194490   64.08250926 
          211           212           213           214           215 
  61.76767266   18.98443472   53.86916821  126.52870820   52.04337248 
          216           217           218           219           220 
  92.72297445   85.56519169   32.51511984   59.17606289  101.24832910 
          221           222           223           224           225 
  -7.58653196    7.26854242   52.28644091  -98.19076756   67.72641399 
          226           227           228           229           230 
  18.25688054  -37.68521096  -63.59668180   11.77970239  -17.29573262 
          231           232           233           234           235 
  14.56581490   -1.46054028   49.17202835  -82.68534862    1.28480994 
          236           237           238           239           240 
  82.79938793   19.90292814  -24.28098007   28.62488636   -3.28829995 
          241           242           243           244           245 
  40.94993860   26.43797568   76.07701663   17.44016165   42.42078568 
          246           247           248           249           250 
  20.82519592   26.23641746   -9.77224861 -286.70178213   25.34169773 
          251           252           253           254           255 
   2.06233784   41.81272864  -20.87581742    4.32901851   38.23780983 
          256           257           258           259           260 
-100.96570163  -39.41745893   -4.65506359  -38.65110423   86.57490052 
          261           262           263           264           265 
 -58.03621103  -23.21597605  -66.38129786   14.23192699   51.06592538 
          266           267           268           269           270 
 -48.17910665   89.93326160 -167.05273655 -196.28096706   14.57700900 
          271           272           273           274           275 
  69.12710325   68.43698836    4.73830969  -45.14788346  103.43656641 
          276           277           278           279           280 
   5.26070395   31.16113338  -36.38278313   73.88600512  -21.68652085 
          281           282           283           284           285 
 -26.12146304   77.57403390   16.11628684  -45.03136407  114.26067554 
          286           287           288           289           290 
  67.02673574  -35.35285308    4.93223043  -12.37630876  -10.50013374 
          291           292           293           294           295 
 -49.84759453   29.31651486   46.26660967   26.80188067   37.57557685 
          296           297           298           299           300 
  76.92206955   26.92185439   57.47931117  -17.24271584   31.59822483 
          301           302           303           304           305 
  59.57637469   -9.00583697   23.36985837   15.40466241 -118.54343815 
          306           307           308           309           310 
  40.51305727   16.76460794   51.54159455    4.04665012    6.93059280 
          311           312           313           314           315 
 -25.86182217 -234.63601201  -23.64585685  -19.07002749  -71.80183627 
          316           317           318           319           320 
-109.45590644   14.20236752    9.92521812   46.24634568 -106.08905344 
          321           322           323           324           325 
  37.12887936  -13.64320848  -25.44152910    8.03119032   -0.01893392 
          326           327           328           329           330 
 -26.77328143    1.20323191   87.61098932  -55.44128376   62.08462196 
          331           332           333           334           335 
 -16.72169719    4.36197937   51.28674337    6.16727680 -102.08728886 
          336           337           338           339           340 
  33.48188463  -40.97930068   25.71178724    6.91571634  -70.25538799 
          341           342           343           344           345 
  83.96380232   51.86530176   -0.62913327   22.08204584   98.05864580 
          346           347           348           349           350 
 -57.11429053   32.83073222   31.02139860  -48.01364568   77.36651751 
          351           352           353           354           355 
  33.84721646    7.28183831  -79.32069379   24.00290791   15.04809146 
          356           357           358           359           360 
  62.46085604   43.18524556   63.57136039   27.51930007   10.33946742 
          361           362           363           364           365 
 -82.47566301  -83.24520184   36.21152691  -10.22337915   33.88287352 
          366           367           368           369           370 
  30.92322578  -98.15204762  -11.43525960  -60.19192686  -75.69449085 
          371           372           373           374           375 
  41.85878802  -28.33909050   29.95556044  -37.13559122   31.57480578 
          376           377           378           379           380 
 108.46792221   52.09638464  -29.84103925  -18.97622512   38.84859084 
          381           382           383           384           385 
-276.69647386  -23.46998770   32.00518365   11.53317265   40.15688925 
          386           387           388           389           390 
  82.95173669 -151.21201172  -16.09994419  103.37318218  -68.60541816 
          391           392           393           394           395 
  51.60107378  117.59344591    3.17474271  -32.25183675  -69.21651513 
          396           397           398           399           400 
  29.32252508   20.16247535   72.28342826   59.87451686  -73.66828925 
          401           402           403           404           405 
  44.73854085   80.57110014   29.87590855   64.60324526   28.88627722 
          406           407           408           409           410 
  30.35375540  -74.92640581    5.36584215   56.19247643   46.10382262 
          411           412           413           414           415 
 -77.65271938   12.00418639  -10.39159938   -2.88765577   42.31987975 
          416           417           418           419           420 
  60.43020566   23.83651378   83.47112452  -62.40849903   30.56385620 
          421           422           423           424           425 
-163.94169188 -180.11493015  -29.69304794   11.34711566   46.68523869 
          426           427           428           429           430 
 -48.17687278   35.36540148   24.81417611  -14.95854644   44.00158236 
          431           432           433           434           435 
 101.40053960    4.03296261  -55.84018025  -26.34479945   62.67353792 
          436           437           438           439           440 
 -15.41619032    9.64160341 -114.94659578   60.98912626    4.83668186 
          441           442           443           444           445 
 -22.75595964 -107.44958853   26.83747936   -2.46698209 -272.11606432 
          446           447           448           449           450 
 -92.32523358   14.66004205   98.76317381 -193.20056167   88.75746213 
          451           452           453           454           455 
  46.07650839   49.64290941  -14.73584262  -12.51007067   60.39282304 
          456           457           458           459           460 
 -53.36765503   -6.46557481  -97.73060294  -50.98487792   58.47104735 
          461           462           463           464           465 
 -38.73237236   64.64127089   37.17554552  -71.40993690  -53.90098130 
          466           467           468           469           470 
   5.57061561  -69.09245607    9.33830506   36.38265570   62.39824314 
          471           472           473           474           475 
  67.99181169   16.48475259   49.88841703 -121.58943860   55.21984080 
          476           477           478           479           480 
 -50.68369118   14.56972311  -46.48842833   32.97767763   15.63970322 
          481           482           483           484           485 
 -27.60951884   57.89943683 -165.02655600   15.66632953   48.30632912 
          486           487           488           489           490 
  48.90656847    0.18663262  -13.96609374   10.08296452   82.73572745 
          491           492           493           494           495 
   2.53326665   87.58299719  -20.08857081  -61.81232121  -23.73387643 
          496           497           498           499           500 
  56.86957408   94.50776242   17.41884844  -45.38884905    9.91994268 
          501           502           503           504           505 
   0.29187278  -11.74617166   -0.26543117  -47.16255279  -30.82373395 
          506           507           508           509           510 
  11.14102372   26.88053646   32.90014599    1.36484931   -0.78204728 
          511           512           513           514           515 
  37.27604681   40.01088233   19.95695240   23.00156172  -11.76868626 
          516           517           518           519           520 
  -3.74007680   35.77075585   53.91814418   11.67437628  -37.91259100 
          521           522           523           524           525 
  44.66590657  117.45341492  -48.71119400   33.66567656  -43.10287720 
          526           527           528           529           530 
 -26.17317790   23.40548021   24.33665524   45.96900094   -2.46531722 
          531           532           533           534           535 
  -9.76669283   28.54097482  -78.99956160 -221.35862279  -55.23339332 
          536           537           538           539           540 
-101.43751172   12.93468121   82.10774833   25.13524292   50.94363995 
          541           542           543           544           545 
  33.10976438   45.85024884  -11.75884905    7.16784191   16.62834442 
          546           547           548           549           550 
   0.74910779  -35.08904391  -41.26400897  -43.68820139   55.89155260 
          551           552           553           554           555 
  68.81191106   39.82438507  -64.12403574  -25.81062699   54.03189491 
          556           557           558           559           560 
  62.72980939   61.83590725    4.96169284 -169.25162888   68.47725583 
          561           562           563           564           565 
  -8.61627716   66.95131714   34.09462311  -42.37041796  -47.27508224 
          566           567           568           569           570 
 -18.38907531   35.54918047   53.08669147 -130.14145343   18.45112153 
          571           572           573           574           575 
   1.83713432    6.32125713   17.09454602   59.18759052 -120.76819900 
          576           577           578           579           580 
 -63.61970416   18.18064810 -101.40551298   52.63160076   10.10086741 
          581           582           583           584           585 
-201.61458783 -184.11468299    3.38518605   -6.86970989  -36.68004274 
          586           587           588           589           590 
  66.94614461   27.53402933    8.12375989   72.31555390   78.34973032 
          591           592           593           594           595 
-143.90501161 -158.96444072  -37.12185275   69.97429217  -98.81635351 
          596           597           598           599           600 
 -58.05930790  -13.75488124   -9.09873707   42.07802002   28.21640677 
          601           602           603           604           605 
  -9.76376173  -18.94537382  -31.65088383   82.55496236   84.95298085 
          606           607           608           609           610 
-140.49613072   -1.29013258   45.22023882  -20.61588696  105.69796049 
          611           612           613           614           615 
  19.05039282   94.25329954   37.86301028  -76.15090630   80.38709065 
          616           617           618           619           620 
-127.31259414   -2.91181223   84.71660776   -1.61272776   45.81046898 
          621           622           623           624           625 
  12.42191637   16.90985912   39.85260788  -50.31480640   53.50263200 
          626           627           628           629           630 
  13.77124221  -87.81864144   19.37215385  -18.46060403   -3.71648496 
          631           632           633           634           635 
  -1.67495924   24.05094457    4.10119910    7.09941974   37.73623528 
          636           637           638           639           640 
 -23.01341403   26.78961767  -45.78086163   56.55344311    7.79066832 
          641           642           643           644           645 
 115.42989718  -69.33745287   27.03021669   74.28579194   55.87728865 
          646           647           648           649           650 
 -40.43497449   47.85556766   30.54445304 -155.46150151 -144.38289436 
          651           652           653           654           655 
 -38.56584344   68.12696656   37.04678389   58.96878877   53.12660627 
          656           657           658           659           660 
  47.40018502   17.83012113  -44.04142169   44.31409581   38.63184560 
          661           662           663           664           665 
 -18.60525953  -36.46532458   21.99186433  -61.95732557   11.42010928 
          666           667           668           669           670 
  18.60120748   52.28572322  -18.13531067   15.02973985   40.48988200 
          671           672           673           674           675 
 -10.00240634   50.69479809   -8.49437465   76.89075626   29.72139785 
          676           677           678           679           680 
 -23.59824185   69.82216993   72.25105744  -27.72660804   64.97637619 
          681           682           683           684           685 
-156.17543110  -15.17465431   23.31258732   17.27138062    2.72890339 
          686           687           688           689           690 
 -34.41973325    8.71311066   82.09021901  -11.47927201    4.04478092 
          691           692           693           694           695 
  20.17458274   -2.96301545   36.92412209  -17.62123486   35.57370302 
          696           697           698           699           700 
-157.58796601   12.74517895   25.39985871   32.73830969   -1.25709060 
          701           702           703           704           705 
  66.31129194   34.83176114   30.14457653   -3.99956591   55.37757022 
          706           707           708           709           710 
  -4.65093259   54.71291172   45.06794700   64.18743286  -18.67036483 
          711           712           713           714           715 
  13.05929394  -32.55094825   -6.92368954   37.97550582   65.40879000 
          716           717           718           719           720 
  48.17709910  -69.12748768  -65.89988295   19.81556998  -56.91398064 
          721           722           723           724           725 
 -51.08067623   -5.41475791  -29.65416686   -1.57243883  -40.41282904 
          726           727           728           729           730 
  98.41056446   49.85098013  -93.63485156   17.33313668  -42.83598790 
          731           732           733           734           735 
  54.57040930    7.75948798 -122.25865609  -52.42697555   -3.43346641 
          736           737           738           739           740 
  36.45081858  -15.03456570   50.53102148   13.64273511   86.99145091 
          741           742           743           744           745 
  -4.34823613   35.81687972  -21.16554240   10.42837419   73.79952510 
          746           747           748           749           750 
  51.84236221   60.63149226    6.86775446   76.85245587   37.13439883 
          751           752           753           754           755 
   2.23999812  -29.68588927   30.84923386    0.08804215  -80.33595725 
          756           757           758           759           760 
 -69.64782270   73.97396402   74.63938030    6.31431662    0.30182421 
          761           762           763           764           765 
  74.44770488   13.88132061   24.48077648  -40.40783770   45.42893480 
          766           767           768           769           770 
  35.89509696   14.47429142   71.32449397  -35.02073814 -142.87714861 
          771           772           773           774           775 
 -22.53015307   44.94048075  -58.14464635 -130.18972678  -68.93346443 
          776           777           778           779           780 
   2.06541815  -32.50007134   -7.53124671   52.07286813    9.43365528 
          781           782           783           784           785 
 -14.68762586   81.08481525   62.70311994  -13.37505173  -33.79589541 
          786           787           788           789           790 
 -58.53146370 -116.23117766  -23.85104688  -24.25825071    6.84967106 
          791           792           793           794           795 
  22.06678696   -6.43851286  -87.34140527    3.65312764  -16.56404106 
          796           797           798           799           800 
  58.18816706  -55.35088900   34.58173404   21.63446332   47.40459145 
          801           802           803           804           805 
 -80.52997436    1.43378251   56.32125182   27.67249938   35.37428345 
          806           807           808           809           810 
   0.12335940   -5.18915473   -3.45161662   94.12665775   34.74320738 
          811           812           813           814           815 
 -37.72177742   -0.43032886  -97.45665578 -137.84316414   -3.95563250 
          816           817           818           819           820 
  -2.47990632  105.71694552   56.46826569   26.03610185    3.67633989 
          821           822           823           824           825 
  34.55484025    8.18742964 -157.74181032  -42.80644369   47.83285164 
          826           827           828           829           830 
   8.93421773   53.08646378   58.75681339  -20.84744184  -66.41351648 
          831           832           833           834           835 
  57.88401401 -148.31493404    4.07250701   38.20842234   -3.19814976 
          836           837           838           839           840 
 -53.68761068  -80.59333844   52.52323994   16.87316585   13.95055070 
          841           842           843           844           845 
  40.03037954  -24.27007904  -78.42879244   35.49013605   -0.72684417 
          846           847           848           849           850 
 -25.77046039    7.67752056   53.00682666 -165.65446109  -14.41889870 
          851           852           853           854           855 
 -11.20724384   53.37222272   -0.45563175   67.89366522 -213.61779751 
          856           857           858           859           860 
  26.62599451  -24.88265407   13.00826161   33.87387003   11.77145744 
          861           862           863           864           865 
  39.19317033    1.27565170  -56.28986728   23.05612555   78.09557454 
          866           867           868           869           870 
  33.47457496    3.92173479   29.56138899   28.67781820   52.50680576 
          871           872           873           874           875 
 -17.12962094  -58.87518700   15.98099348   59.61648476   42.92036919 
          876           877           878           879           880 
  68.50028249   28.12965050  101.13294339   40.98012659   20.75375764 
          881           882           883           884           885 
 -29.57060171   49.43056132 -165.12826058   63.57527432  -37.38804467 
          886           887           888           889           890 
 -30.25722736   13.06411727   52.20194497   59.61033820   -8.23355121 
          891           892           893           894           895 
  75.16891518  -29.23264113   47.24073296  -23.36740281    3.17021676 
          896           897           898           899           900 
  -2.92468224  -42.36427950    4.66434462   68.82109408  -92.78498982 
          901           902           903           904           905 
  15.96797459   34.60963741   24.14041353   -7.84975464   54.30607092 
          906           907           908           909           910 
  49.43768873  -89.07446591    2.19411753  -29.83676129   25.17286010 
          911           912           913           914           915 
 -17.15618127    5.91135541 -101.96930607  -47.84680372  -17.50959832 
          916           917           918           919           920 
 -90.98219937 -135.37465888   42.01845939  -17.23831984   -9.90104231 
          921           922           923           924           925 
 -91.40669821   86.43358921   42.11758970  -53.90949214  102.59327045 
          926           927           928           929           930 
  30.55035087   37.48081387   15.79582940   70.37185902   44.49979291 
          931           932           933           934           935 
  12.40724241  -83.62525620   59.67409465   20.74233634    5.82305148 
          936           937           938           939           940 
  47.28065423   -8.66813111 -117.81012032   32.23898139   39.38926616 
          941           942           943           944           945 
  52.60912121  -24.84045617   62.85409009   -2.19145227   76.66617030 
          946           947           948           949           950 
  37.39448055   27.12807695   35.46975817   55.24003376   48.21952843 
          951           952           953           954           955 
  55.28133056   28.89212110   48.48236221 -148.43336405   37.41267021 
          956           957           958           959           960 
  76.24197085    8.01463803   -1.59344107  -53.57242018   -2.12335975 
          961           962           963           964           965 
  35.62938371   77.29822250 -185.45066437   22.57411993  -43.35680480 
          966           967           968           969           970 
  43.95359138   38.67114856   16.94779069   39.27729942   -9.69558584 
          971           972           973           974           975 
  25.79565402   24.00690234   -2.28241146  -33.55405025  -17.38392418 
          976           977           978           979           980 
  -0.60356455   65.12954716  -20.99743339   31.72518332  -48.13450065 
          981           982           983           984           985 
  70.30865623   38.98937301  -16.50083976    8.82672968    0.17524299 
          986           987           988           989           990 
   9.87041918  -89.97739885    1.59445346   71.20956522   63.71749843 
          991           992           993           994           995 
  43.54502469   17.26232864   28.86682932   64.30400530  -65.07350504 
          996           997           998           999          1000 
  24.48380962   78.76138443  -34.33120775   28.36308943   21.88313403 
         1001          1002          1003          1004          1005 
 -56.55425689   47.83457952   44.73424027   34.57604225   17.71597577 
         1006          1007          1008          1009          1010 
 -70.77339721   62.62305278   53.28990720   -7.54633825  -42.17346525 
         1011          1012          1013          1014          1015 
 111.83057351  -16.33850203 -104.97696146  -41.13931029  -45.72041721 
         1016          1017          1018          1019          1020 
  16.62989725   31.34368586  102.86249209   28.92034923   -2.82158181 
         1021          1022          1023          1024          1025 
 -19.14800613  -69.76519653  -13.99034617  -34.88912000  -89.25826099 
         1026          1027          1028          1029          1030 
  42.61699449   42.75354174   63.65206002   -1.01652590  -38.46639056 
         1031          1032          1033          1034          1035 
  75.97515042   51.98512862  -28.04432534   -4.05885055   47.32799665 
         1036          1037          1038          1039          1040 
  24.82178144  110.29874906  -41.42221463  -36.82536347   11.73959805 
         1041          1042          1043          1044          1045 
  35.58082811   43.35464607   98.91848399  -90.09931138  -19.07194708 
         1046          1047          1048          1049          1050 
   9.15235806 -122.50007134  -11.94061622    1.20464831   68.64914002 
         1051          1052          1053          1054          1055 
  57.81795579   54.47288454    4.35816399  -53.16017875  -18.66700580 
         1056          1057          1058          1059          1060 
  -1.08672416   15.23186276   55.98455664   39.20743196   22.14000085 
         1061          1062          1063          1064          1065 
  65.85583520   37.40119372  -69.00591870   39.77590623  -13.37052073 
         1066          1067          1068          1069          1070 
  72.37883012   18.48588103   -2.52805536   91.72756266   57.50426289 
         1071          1072          1073          1074          1075 
  -5.81523126   25.23225256  -42.36467338    4.20053388  -85.37882310 
         1076          1077          1078          1079          1080 
  13.49611186    2.31437172   23.65793780  -61.92516827  -15.40462802 
         1081          1082          1083          1084          1085 
-227.80366229  -39.01913252   12.99346184   55.84421758  -26.10016731 
         1086          1087          1088          1089          1090 
 -38.96768860   -6.24849638  -29.63949555   73.90485462   53.97409241 
         1091          1092          1093          1094          1095 
  39.66977739    1.80157847   87.95710373  126.94472133   77.12571941 
         1096          1097          1098          1099          1100 
 -41.04639934  -82.70146030    3.31664216   -7.90179622  -22.54554546 
         1101          1102          1103          1104          1105 
  37.26898561  -63.37513429   57.91143797   71.41748733   63.58170884 
         1106          1107          1108          1109          1110 
  84.44677170   56.75331255   -1.57215189 -331.24405903  -42.19102583 
         1111          1112          1113          1114          1115 
  62.48395250   23.67637279  -86.52007482   67.95251927    5.13031681 
         1116          1117          1118          1119          1120 
  38.05681182  -33.33927889   51.10731269  -11.37251914 -250.40495591 
         1121          1122          1123          1124          1125 
  10.25707622   40.75304385 -175.54997776  -98.66354003   -1.56263111 
         1126          1127          1128          1129          1130 
  40.24423156   13.05608319   68.84713896  -64.51070673    6.14321276 
         1131          1132          1133          1134          1135 
  14.80898030  -76.64352137   48.12955079   10.01663379   89.83244809 
         1136          1137          1138          1139          1140 
-124.86793427 -128.39144008    4.95048879   -2.25421337   72.07443820 
         1141          1142          1143          1144          1145 
 -17.76283360  -98.51628546   29.95981811  -74.10247024   66.97565170 
         1146          1147          1148          1149          1150 
  19.95331711   14.32007338  -24.35689715   17.32415357   40.60491006 
         1151          1152          1153          1154          1155 
 -21.35035993   33.46104552 -111.29582287   -8.06976724   -1.07381146 
         1156          1157          1158          1159          1160 
  14.38915759 -163.25951312   36.51928168   77.09674344  -34.33891552 
         1161          1162          1163          1164          1165 
 -32.72999724 -138.16334640   10.70541823  -18.77463756  -12.81279995 
         1166          1167          1168          1169          1170 
  56.53726107  -69.43876093  -21.76165068 -210.42454383  -44.65248108 
         1171          1172          1173          1174          1175 
 -40.18318130    5.35293113   15.93192086   39.38102877  -55.19005575 
         1176          1177          1178          1179          1180 
  -4.48476969  -51.58241139  -26.23610859  -97.22304768   77.44058087 
         1181          1182          1183          1184          1185 
-188.79621940  -39.74623391   22.23264950  -19.53527990   27.50383331 
         1186          1187          1188          1189          1190 
 131.51389257   51.30940251  -22.27877106   21.45922904   11.73560587 
         1191          1192          1193          1194          1195 
  59.96661797   -3.01914294   34.44723710   84.32201948   22.39244054 
         1196          1197          1198          1199          1200 
  10.69421657  -58.46893732   12.40488411    5.23490400  -32.60523325 
         1201          1202          1203          1204          1205 
 -24.69353902 -259.15746274   34.28271911   42.41315732   56.92138559 
         1206          1207          1208          1209          1210 
  40.97426282  -41.36302921   47.40102379  -57.06055289    2.96121163 
         1211          1212          1213          1214          1215 
  23.17024809   51.82388147   17.75328578   -7.57240799  -55.12637946 
         1216          1217          1218          1219          1220 
  42.30595861  -32.77915016   71.49003974   18.72810447  -42.34182217 
         1221          1222          1223          1224          1225 
  25.97885532   17.17532049   90.22113106    5.25808492  -43.12853010 
         1226          1227          1228          1229          1230 
  52.53631816   44.18547142   67.77882058    5.28377720   41.53541796 
         1231          1232          1233          1234          1235 
 -34.36114667    5.66961304  -82.03896675  -32.94218015 -110.43932297 
         1236          1237          1238          1239          1240 
  68.22630856  -20.19296206   87.32834592  -15.12563366   62.86135576 
         1241          1242          1243          1244          1245 
-110.15535285  -88.58815548   64.70377529   30.01717328 -131.36246145 
         1246          1247          1248          1249          1250 
   9.26475872   46.33506229   40.53950215   13.29532845    4.53072036 
         1251          1252          1253          1254          1255 
 -71.35905277  -48.07942675   -3.52256382    8.16473740   60.32032907 
         1256          1257          1258          1259          1260 
 -50.60848793   -1.59546086  -62.88343045  -20.55982574  -27.43259548 
         1261          1262          1263          1264          1265 
   9.83233817   48.19297588  -54.11677123   -6.86035522   22.35998710 
         1266          1267          1268          1269          1270 
  24.34393452 -173.94583805   11.83624440  -88.83523440   22.57757377 
         1271          1272          1273          1274          1275 
-103.89071641 -207.05667533  -22.03392070   52.61359534 -123.73761491 
         1276          1277          1278          1279          1280 
  -2.46830227   22.24371256 -192.07799543   74.62426424  -14.11095098 
         1281          1282          1283          1284          1285 
  20.17870894   -9.52429386   18.79023426   74.60686842  -58.64167737 
         1286          1287          1288          1289          1290 
  46.75461208   87.76033098   31.35205014  -75.00110647    6.52392813 
         1291          1292          1293          1294          1295 
  37.89254829   33.61000616  -39.86015730    7.45280812  -69.33703945 
         1296          1297          1298          1299          1300 
  -1.04880968   68.05164884 -103.41052769    8.22686113   48.05464832 
         1301          1302          1303          1304          1305 
  -6.42419232   82.67806791  -33.52214045  -97.57451026  -51.51013632 
         1306          1307          1308          1309          1310 
  -0.98492376   13.19974251   28.10280690  -44.75071717   55.38638572 
         1311          1312          1313          1314          1315 
  66.36218956  117.03929155   19.11818206  -28.05657854   44.89525279 
         1316          1317          1318          1319          1320 
  15.32152583  -47.55024183   38.73131100    6.88290866  132.79781779 
         1321          1322          1323          1324          1325 
-114.93439854  -27.29867374  -81.68316380   56.87840054  -32.54901987 
         1326          1327          1328          1329          1330 
  11.28529447  -13.08530080   -3.97173199   58.17726114   46.68899249 
         1331          1332          1333          1334          1335 
  46.65524591  -45.76265168   11.62325322   48.09518863  -97.95247439 
         1336          1337          1338          1339          1340 
 -46.27681019  -50.13638906    6.67393882 -138.69977553   32.25878918 
         1341          1342          1343          1344          1345 
  28.20023201    7.90486239  -61.50700927  -95.32918837   30.03637279 
         1346          1347          1348          1349          1350 
   9.03356394   43.44659973    1.90338242  -46.73615756   38.78735397 
         1351          1352          1353          1354          1355 
  16.73971118  -21.94987035  -71.03766688   57.20641215   81.33995461 
         1356          1357          1358          1359          1360 
  18.95712595   39.83225787   13.40710864  -33.05311449 -137.86748992 
         1361          1362          1363          1364          1365 
  85.97441954   18.70015784   -4.90967093  -31.43917113    0.99747440 
         1366          1367          1368          1369          1370 
  28.51850373  -11.42174650   55.42909187   30.51624365  -11.44625461 
         1371          1372          1373          1374          1375 
  50.36800660   49.99074182   20.18303009   20.35019305  -25.70109585 
         1376          1377          1378          1379          1380 
  32.31335001   -6.59217982   45.53477984   31.46186291   36.38394563 
         1381          1382          1383          1384          1385 
  50.22913878   62.75642502 -247.39273008  -35.58228947  -27.75531961 
         1386          1387          1388          1389          1390 
 -14.54518169  -75.41324893   21.14381881   28.48821910    9.50881744 
         1391          1392          1393          1394          1395 
  23.51595753  -31.22868287   55.66696418   -2.12137544    0.58278641 
         1396          1397          1398          1399          1400 
  -2.74250729   59.35685425  -93.40781856  -20.87538253   34.27412489 
         1401          1402          1403          1404          1405 
 -73.97318968   58.62568038  -99.27820794   92.37443281  -78.76644600 
         1406          1407          1408          1409          1410 
-108.16371399    5.05528561  -95.79444412   41.76493915  -68.68655465 
         1411          1412          1413          1414          1415 
  24.85066533  -37.26422297  -27.99838665   31.30502469   36.74157282 
         1416          1417          1418          1419          1420 
 -79.22559238   25.60837609    2.38419130   76.55632265   86.10544806 
         1421          1422          1423          1424          1425 
   8.02002762   31.27901189   17.11827563 -170.54177667  -44.54018455 
         1426          1427          1428          1429          1430 
 -28.76815433  114.89234505   43.27242140  -40.12186161   11.75852022 
         1431          1432          1433          1434          1435 
  53.53928699    6.80300422   21.38505766    8.73721687  -47.52158406 
         1436          1437          1438          1439          1440 
  -1.10329212   22.14221775   71.13264153  -24.79972099  -12.53986198 
         1441          1442          1443          1444          1445 
  18.70092360   71.13368619   -4.41258759    1.59196214  -27.62489699 
         1446          1447          1448          1449          1450 
 -39.61178628  -88.96595452  114.52914914 -144.06682271  -24.50646971 
         1451          1452          1453          1454          1455 
 -49.80279341   44.45029618  -43.44473230  -50.33880553  -24.44895414 
         1456          1457          1458          1459          1460 
  -3.61335294  -44.89841417   27.82995154    1.98743196  -25.03209951 
         1461          1462          1463          1464          1465 
  39.52018644  -88.60709059    6.81745906  -25.64778573    7.95769404 
         1466          1467          1468          1469          1470 
 -15.93813881   21.18514088  -51.19065103  -49.59800190   -9.36823579 
         1471          1472          1473          1474          1475 
 -89.31489957   53.67739408  -20.73012686   29.31701356  -93.30471166 
         1476          1477 
  78.23542435    0.81406672 </code></pre>
</div>
</div>
<p>The qqnorm() function creates the normal probability plot, and the qqline() function adds a reference line to help evaluate how closely the residuals (difference between the actual and predicted values) follow a normal distribution.</p>
<p>The residuals are normally distributed, since I see that they follow the reference line. If they were to deviate significantly from the reference line, it would indicate a violation of the normality assumption of linear regression.</p>
<p>Another type of prediction, using the model_age from earlier:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>new_customer_age <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Age =</span> <span class="dv">35</span>)</span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>new_customer_age<span class="sc">$</span>Age_sq <span class="ot">&lt;-</span> new_customer_age<span class="sc">$</span>Age<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>predicted_purchase_amount_age <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_age, <span class="at">newdata =</span> new_customer_age)</span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(predicted_purchase_amount_age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
600.2937 </code></pre>
</div>
</div>
<p>Based on the age of the new customer, an amount around 600 euro can be expected as purchase value. This is close to the earlier predicted value as well.</p>
<p><strong>d.</strong> Finally, repeat steps 1b (dummy variables, outlier deletion), 1c (check for multicollinearity), and 1d (Check if there are non-linear relationships between the independent variables and the dependent variable), so that this time the missing values are still included. Then take the appropriate steps to impute the missing values.<br>
Describe whether there are differences between the imputed vs non-imputed models and whether imputation is an appropriate solution in this case.</p>
<p>To repeat the steps with missing values included using the original rawDF dataset:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make a copy of the rawDF dataset</span></span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a><span class="co">#part2da</span></span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>webshop_missing_data <span class="ot">&lt;-</span> rawDF</span>
<span id="cb99-4"><a href="#cb99-4" aria-hidden="true" tabindex="-1"></a><span class="co">#remove negative values</span></span>
<span id="cb99-5"><a href="#cb99-5" aria-hidden="true" tabindex="-1"></a>webshop_missing_data <span class="ot">&lt;-</span> webshop_missing_data <span class="sc">%&gt;%</span></span>
<span id="cb99-6"><a href="#cb99-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Time_Spent_on_Website <span class="sc">&gt;=</span> <span class="dv">0</span> <span class="sc">&amp;</span> Number_of_products_browsed <span class="sc">&gt;=</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(webshop_missing_data[,<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">8</span>,<span class="dv">9</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="version1_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here, I noticed that if I remove the outliers other than the negative values, or try to average time spent and products browsed, it deletes too many rows with NA values, to the point that only those NA values are left that completely do not have any values within the whole row. this is not nice because I will want to predict missing values for people who only have one cell missing in a row for example.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>webshop_missing_data <span class="ot">&lt;-</span> webshop_missing_data <span class="sc">%&gt;%</span></span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Find_website_dummy_2 =</span> <span class="fu">if_else</span>(<span class="fu">is.na</span>(Find_website), <span class="cn">NA_integer_</span>, </span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a>                                        <span class="fu">recode</span>(Find_website, </span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a>                                               <span class="st">`</span><span class="at">Social_Media_Advertisement</span><span class="st">`</span> <span class="ot">=</span> <span class="dv">1</span>, </span>
<span id="cb101-5"><a href="#cb101-5" aria-hidden="true" tabindex="-1"></a>                                               <span class="st">`</span><span class="at">Search_Engine</span><span class="st">`</span> <span class="ot">=</span> <span class="dv">2</span>, </span>
<span id="cb101-6"><a href="#cb101-6" aria-hidden="true" tabindex="-1"></a>                                               <span class="st">`</span><span class="at">Friends_or_Family</span><span class="st">`</span> <span class="ot">=</span> <span class="dv">3</span>, </span>
<span id="cb101-7"><a href="#cb101-7" aria-hidden="true" tabindex="-1"></a>                                               <span class="st">`</span><span class="at">Other</span><span class="st">`</span> <span class="ot">=</span> <span class="dv">4</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb101-8"><a href="#cb101-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>Find_website)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Above I use the if_else() function from dplyr to create the dummy variable, while preserving the missing values. In this case, we use (is.na(Find_website) as the logical vector, which is TRUE for missing values and FALSE for non-missing values. If the value is missing, we keep it as NA_integer_, otherwise I use the recode() function to convert the original values to the dummy variable values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a copy of the original dataset</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>webshop_imputed <span class="ot">&lt;-</span> webshop_missing_data</span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb102-5"><a href="#cb102-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb102-6"><a href="#cb102-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-7"><a href="#cb102-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform regression imputation</span></span>
<span id="cb102-8"><a href="#cb102-8" aria-hidden="true" tabindex="-1"></a>webshop_imputed <span class="ot">&lt;-</span> <span class="fu">mice</span>(webshop_imputed, <span class="at">m=</span><span class="dv">5</span>, <span class="at">method=</span><span class="st">"norm.predict"</span>, <span class="at">seed=</span><span class="dv">123</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 iter imp variable
  1   1  Ease_of_purchase  Find_website_dummy_2
  1   2  Ease_of_purchase  Find_website_dummy_2
  1   3  Ease_of_purchase  Find_website_dummy_2
  1   4  Ease_of_purchase  Find_website_dummy_2
  1   5  Ease_of_purchase  Find_website_dummy_2
  2   1  Ease_of_purchase  Find_website_dummy_2
  2   2  Ease_of_purchase  Find_website_dummy_2
  2   3  Ease_of_purchase  Find_website_dummy_2
  2   4  Ease_of_purchase  Find_website_dummy_2
  2   5  Ease_of_purchase  Find_website_dummy_2
  3   1  Ease_of_purchase  Find_website_dummy_2
  3   2  Ease_of_purchase  Find_website_dummy_2
  3   3  Ease_of_purchase  Find_website_dummy_2
  3   4  Ease_of_purchase  Find_website_dummy_2
  3   5  Ease_of_purchase  Find_website_dummy_2
  4   1  Ease_of_purchase  Find_website_dummy_2
  4   2  Ease_of_purchase  Find_website_dummy_2
  4   3  Ease_of_purchase  Find_website_dummy_2
  4   4  Ease_of_purchase  Find_website_dummy_2
  4   5  Ease_of_purchase  Find_website_dummy_2
  5   1  Ease_of_purchase  Find_website_dummy_2
  5   2  Ease_of_purchase  Find_website_dummy_2
  5   3  Ease_of_purchase  Find_website_dummy_2
  5   4  Ease_of_purchase  Find_website_dummy_2
  5   5  Ease_of_purchase  Find_website_dummy_2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Number of logged events: 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the imputed data</span></span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>webshop_imputed <span class="ot">&lt;-</span> <span class="fu">complete</span>(webshop_imputed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This imputation causes the dummy variable to leave the given dimensions of integers and become a float value. This might make it harder to interpret.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot of Age vs. Purchase_Amount</span></span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(webshop_imputed<span class="sc">$</span>Age, webshop_missing_data<span class="sc">$</span>Purchase_Amount)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="version1_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot of Shipping_Time vs. Purchase_Amount</span></span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(webshop_imputed<span class="sc">$</span>Shipping_Time, webshop_missing_data<span class="sc">$</span>Purchase_Amount)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="version1_files/figure-html/unnamed-chunk-38-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Scatter plot of Pictures vs. Purchase_Amount</span></span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(webshop_imputed<span class="sc">$</span>Pictures, webshop_missing_data<span class="sc">$</span>Purchase_Amount)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="version1_files/figure-html/unnamed-chunk-38-3.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="co">#make average of the 2 correlating columns</span></span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a>webshop_imputed<span class="sc">$</span>Time_Products_Average <span class="ot">&lt;-</span> (webshop_imputed<span class="sc">$</span>Time_Spent_on_Website<span class="sc">/</span><span class="dv">60</span> <span class="sc">+</span> webshop_imputed<span class="sc">$</span>Number_of_products_browsed)<span class="sc">/</span><span class="dv">2</span></span>
<span id="cb109-3"><a href="#cb109-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb109-4"><a href="#cb109-4" aria-hidden="true" tabindex="-1"></a>webshop_imputed<span class="sc">$</span>Time_Spent_on_Website <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb109-5"><a href="#cb109-5" aria-hidden="true" tabindex="-1"></a>webshop_imputed<span class="sc">$</span>Number_of_products_browsed <span class="ot">&lt;-</span> <span class="cn">NULL</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(webshop_imputed, <span class="fu">aes</span>(<span class="at">x =</span> Find_website_dummy_2, <span class="at">y =</span> Purchase_Amount)) <span class="sc">+</span></span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb110-4"><a href="#cb110-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Find Website Dummy"</span>, <span class="at">y =</span> <span class="st">"Purchase Amount"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="version1_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Above we see that the plot looks less organized than earlier.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(webshop_imputed, <span class="fu">aes</span>(<span class="at">x =</span> Device, <span class="at">y =</span> Purchase_Amount)) <span class="sc">+</span></span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb112-4"><a href="#cb112-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Device"</span>, <span class="at">y =</span> <span class="st">"Purchase Amount"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="version1_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><br>
Now, lets run the regressions again!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Purchase_Amount<span class="sc">~</span>Time_Products_Average,<span class="at">data=</span>webshop_imputed))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Time_Products_Average, data = webshop_imputed)

Residuals:
    Min      1Q  Median      3Q     Max 
-416.86  -30.15   10.66   44.93  179.18 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            379.754      4.937   76.91   &lt;2e-16 ***
Time_Products_Average   12.488      0.274   45.59   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 69.46 on 1853 degrees of freedom
Multiple R-squared:  0.5286,    Adjusted R-squared:  0.5284 
F-statistic:  2078 on 1 and 1853 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Purchase_Amount<span class="sc">~</span>Pictures,<span class="at">data=</span>webshop_imputed))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Pictures, data = webshop_imputed)

Residuals:
    Min      1Q  Median      3Q     Max 
-476.45  -59.75    4.42   68.59  271.03 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  588.561      7.887  74.626   &lt;2e-16 ***
Pictures       1.293      2.485   0.521    0.603    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 101.2 on 1853 degrees of freedom
Multiple R-squared:  0.0001462, Adjusted R-squared:  -0.0003934 
F-statistic: 0.271 on 1 and 1853 DF,  p-value: 0.6027</code></pre>
</div>
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Purchase_Amount<span class="sc">~</span>Shipping_Time,<span class="at">data=</span>webshop_imputed))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Shipping_Time, data = webshop_imputed)

Residuals:
    Min      1Q  Median      3Q     Max 
-474.93  -59.80    4.44   68.56  268.78 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   595.3420     7.7243  77.074   &lt;2e-16 ***
Shipping_Time  -0.9494     2.4410  -0.389    0.697    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 101.2 on 1853 degrees of freedom
Multiple R-squared:  8.163e-05, Adjusted R-squared:  -0.000458 
F-statistic: 0.1513 on 1 and 1853 DF,  p-value: 0.6974</code></pre>
</div>
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Purchase_Amount<span class="sc">~</span>Review_rating,<span class="at">data=</span>webshop_imputed))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Review_rating, data = webshop_imputed)

Residuals:
    Min      1Q  Median      3Q     Max 
-471.90  -60.16    3.46   68.05  277.67 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    473.583     19.262  24.586  &lt; 2e-16 ***
Review_rating   29.841      4.799   6.218 6.21e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 100.1 on 1853 degrees of freedom
Multiple R-squared:  0.02044,   Adjusted R-squared:  0.01991 
F-statistic: 38.66 on 1 and 1853 DF,  p-value: 6.206e-10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Purchase_Amount<span class="sc">~</span>Ease_of_purchase,<span class="at">data=</span>webshop_imputed))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Ease_of_purchase, data = webshop_imputed)

Residuals:
    Min      1Q  Median      3Q     Max 
-474.41  -59.86    4.29   68.76  269.19 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       582.327     17.842  32.638   &lt;2e-16 ***
Ease_of_purchase    2.536      4.418   0.574    0.566    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 101.2 on 1853 degrees of freedom
Multiple R-squared:  0.0001778, Adjusted R-squared:  -0.0003618 
F-statistic: 0.3295 on 1 and 1853 DF,  p-value: 0.566</code></pre>
</div>
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Purchase_Amount<span class="sc">~</span>Age,<span class="at">data=</span>webshop_imputed))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Age, data = webshop_imputed)

Residuals:
    Min      1Q  Median      3Q     Max 
-516.13  -60.59    2.39   67.88  266.40 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 649.2598    10.8211  59.999  &lt; 2e-16 ***
Age          -1.2558     0.2337  -5.373 8.71e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 100.4 on 1853 degrees of freedom
Multiple R-squared:  0.01534,   Adjusted R-squared:  0.01481 
F-statistic: 28.87 on 1 and 1853 DF,  p-value: 8.71e-08</code></pre>
</div>
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Purchase_Amount<span class="sc">~</span>Device,<span class="at">data=</span>webshop_imputed))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Device, data = webshop_imputed)

Residuals:
    Min      1Q  Median      3Q     Max 
-466.92  -59.97    4.20   68.38  266.26 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  584.982      4.432 131.991   &lt;2e-16 ***
DevicePC      10.419      5.224   1.994   0.0463 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 101.1 on 1853 degrees of freedom
Multiple R-squared:  0.002142,  Adjusted R-squared:  0.001603 
F-statistic: 3.978 on 1 and 1853 DF,  p-value: 0.04626</code></pre>
</div>
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Purchase_Amount<span class="sc">~</span>Find_website_dummy_2,<span class="at">data=</span>webshop_imputed))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Find_website_dummy_2, data = webshop_imputed)

Residuals:
    Min      1Q  Median      3Q     Max 
-475.53  -59.84    4.65   69.08  268.07 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           595.066      6.986  85.178   &lt;2e-16 ***
Find_website_dummy_2   -1.476      3.756  -0.393    0.694    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 101.2 on 1853 degrees of freedom
Multiple R-squared:  8.335e-05, Adjusted R-squared:  -0.0004563 
F-statistic: 0.1545 on 1 and 1853 DF,  p-value: 0.6943</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a>model_d <span class="ot">&lt;-</span> <span class="fu">lm</span>(Purchase_Amount <span class="sc">~</span> Time_Products_Average<span class="sc">+</span>Review_rating<span class="sc">+</span>Ease_of_purchase<span class="sc">+</span>Pictures<span class="sc">+</span>Find_website_dummy_2<span class="sc">+</span>Shipping_Time<span class="sc">+</span>Device, <span class="at">data =</span> webshop_imputed)</span>
<span id="cb130-2"><a href="#cb130-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Time_Products_Average + Review_rating + 
    Ease_of_purchase + Pictures + Find_website_dummy_2 + Shipping_Time + 
    Device, data = webshop_imputed)

Residuals:
    Min      1Q  Median      3Q     Max 
-430.67  -28.67   11.95   42.30  155.88 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           230.4089    19.9671  11.539  &lt; 2e-16 ***
Time_Products_Average  12.5856     0.2661  47.288  &lt; 2e-16 ***
Review_rating          32.9951     3.2332  10.205  &lt; 2e-16 ***
Ease_of_purchase        6.5842     2.9476   2.234  0.02562 *  
Pictures               -1.1795     1.6566  -0.712  0.47655    
Find_website_dummy_2   -4.4164     2.5034  -1.764  0.07788 .  
Shipping_Time          -1.7862     1.6259  -1.099  0.27209    
DevicePC                9.1110     3.4873   2.613  0.00906 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 67.38 on 1847 degrees of freedom
Multiple R-squared:  0.5579,    Adjusted R-squared:  0.5563 
F-statistic:   333 on 7 and 1847 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a>scaled_data2 <span class="ot">&lt;-</span> webshop_imputed</span>
<span id="cb132-2"><a href="#cb132-2" aria-hidden="true" tabindex="-1"></a>scaled_data2[, <span class="fu">c</span>(<span class="st">"Time_Products_Average"</span>, <span class="st">"Review_rating"</span>, <span class="st">"Ease_of_purchase"</span>)] <span class="ot">&lt;-</span> <span class="fu">scale</span>(scaled_data2[, <span class="fu">c</span>(<span class="st">"Time_Products_Average"</span>, <span class="st">"Review_rating"</span>, <span class="st">"Ease_of_purchase"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a>model_e <span class="ot">&lt;-</span> <span class="fu">lm</span>(Purchase_Amount <span class="sc">~</span> Time_Products_Average<span class="sc">+</span>Review_rating<span class="sc">+</span>Ease_of_purchase<span class="sc">+</span>Find_website_dummy_2<span class="sc">+</span>Device, <span class="at">data =</span> scaled_data2)</span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_e)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Time_Products_Average + Review_rating + 
    Ease_of_purchase + Find_website_dummy_2 + Device, data = scaled_data2)

Residuals:
    Min      1Q  Median      3Q     Max 
-430.44  -28.46   12.04   42.23  151.74 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            593.740      5.316 111.694  &lt; 2e-16 ***
Time_Products_Average   74.056      1.566  47.285  &lt; 2e-16 ***
Review_rating           16.000      1.567  10.213  &lt; 2e-16 ***
Ease_of_purchase         3.531      1.567   2.254  0.02432 *  
Find_website_dummy_2    -4.453      2.503  -1.779  0.07541 .  
DevicePC                 9.088      3.487   2.606  0.00922 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 67.37 on 1849 degrees of freedom
Multiple R-squared:  0.5575,    Adjusted R-squared:  0.5563 
F-statistic:   466 on 5 and 1849 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare the models</span></span>
<span id="cb135-2"><a href="#cb135-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_c)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Time_Products_Average + Review_rating + 
    Ease_of_purchase, data = webshop_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-331.24  -29.23    8.93   41.54  143.31 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           213.9735    18.3789  11.642   &lt;2e-16 ***
Time_Products_Average  12.4548     0.2704  46.055   &lt;2e-16 ***
Review_rating          36.2973     3.4054  10.659   &lt;2e-16 ***
Ease_of_purchase        6.1140     2.8152   2.172     0.03 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 61.87 on 1473 degrees of freedom
Multiple R-squared:  0.6019,    Adjusted R-squared:  0.6011 
F-statistic: 742.3 on 3 and 1473 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Time_Products_Average + Review_rating + 
    Ease_of_purchase + Pictures + Find_website_dummy_2 + Shipping_Time + 
    Device, data = webshop_imputed)

Residuals:
    Min      1Q  Median      3Q     Max 
-430.67  -28.67   11.95   42.30  155.88 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           230.4089    19.9671  11.539  &lt; 2e-16 ***
Time_Products_Average  12.5856     0.2661  47.288  &lt; 2e-16 ***
Review_rating          32.9951     3.2332  10.205  &lt; 2e-16 ***
Ease_of_purchase        6.5842     2.9476   2.234  0.02562 *  
Pictures               -1.1795     1.6566  -0.712  0.47655    
Find_website_dummy_2   -4.4164     2.5034  -1.764  0.07788 .  
Shipping_Time          -1.7862     1.6259  -1.099  0.27209    
DevicePC                9.1110     3.4873   2.613  0.00906 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 67.38 on 1847 degrees of freedom
Multiple R-squared:  0.5579,    Adjusted R-squared:  0.5563 
F-statistic:   333 on 7 and 1847 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_e)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Purchase_Amount ~ Time_Products_Average + Review_rating + 
    Ease_of_purchase + Find_website_dummy_2 + Device, data = scaled_data2)

Residuals:
    Min      1Q  Median      3Q     Max 
-430.44  -28.46   12.04   42.23  151.74 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            593.740      5.316 111.694  &lt; 2e-16 ***
Time_Products_Average   74.056      1.566  47.285  &lt; 2e-16 ***
Review_rating           16.000      1.567  10.213  &lt; 2e-16 ***
Ease_of_purchase         3.531      1.567   2.254  0.02432 *  
Find_website_dummy_2    -4.453      2.503  -1.779  0.07541 .  
DevicePC                 9.088      3.487   2.606  0.00922 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 67.37 on 1849 degrees of freedom
Multiple R-squared:  0.5575,    Adjusted R-squared:  0.5563 
F-statistic:   466 on 5 and 1849 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>Model C:</strong></p>
<pre><code>Multiple R-squared:  0.6019,    Adjusted R-squared:  0.6011</code></pre>
<p>All predictor variables have statistically significant coefficients, as indicated by the p-values less than 0.05. The R-squared value of 0.6019 indicates that the model explains approximately 60.2% of the variance in the response variable, Purchase_Amount.</p>
<p><strong>Model D:</strong></p>
<pre><code>Multiple R-squared:  0.5579,    Adjusted R-squared:  0.5563 </code></pre>
<p>Again, all predictor variables have statistically significant coefficients except for Pictures and Shipping_Time, as indicated by their p-values greater than 0.05.<br>
<br>
The R-squared value of 0.5579 indicates that this model explains approximately 55.8% of the variance in the response variable. This is less than in model_c.</p>
<p><strong>Model E:</strong></p>
<pre><code>Multiple R-squared:  0.5575,    Adjusted R-squared:  0.5563</code></pre>
<p>For the third model (model_e), a subset of the predictor variables from model_d is used: Time_Products_Average, Review_rating, Ease_of_purchase, Find_website_dummy_2, and Device. All predictor variables have statistically significant coefficients except for Find_website_dummy_2, as indicated by its p-value greater than 0.05. The R-squared value of 0.5575 indicates that this model explains approximately 55.8% of the variance in the response variable.</p>
</section>
<section id="reflection" class="level3">
<h3 class="anchored" data-anchor-id="reflection">Reflection</h3>
<p>There are several ways to impute missing data, including:</p>
<ol type="1">
<li><p>Mean or median imputation: Replace missing values with the mean or median of the observed data for that variable.</p></li>
<li><p>Last observation carried forward (LOCF): Use the last observed value of a variable to fill in any missing values that follow it in time.</p></li>
<li><p>Multiple imputation: Generate multiple sets of plausible values for missing data based on statistical models of the observed data, and combine the results to obtain a single imputed dataset.</p></li>
<li><p>Regression imputation: Predict missing values for a variable using other variables in the dataset that are related to it through a regression model.</p></li>
<li><p>K-nearest neighbor (KNN) imputation: Use the values of the k-nearest observations in the dataset to predict the missing value for a variable.</p></li>
<li><p>Expectation-Maximization (EM) algorithm: Estimate the parameters of a statistical model that includes missing data using an iterative algorithm that alternates between imputing the missing values and updating the model parameters.</p></li>
</ol>
<p>Each method has strengths and weaknesses, and it is important to carefully evaluate the limitations of each method before choosing.</p>
<p>Personally, I used multiple imputations. It uses the MICE (Multivariate Imputation by Chained Equations) package in R to impute missing values by modeling each variable with missing data as a function of the other variables in the dataset. In this code, a copy of the original dataset with missing data is created, then MICE is used to perform imputation on this copy using the “norm.predict” method, which uses regression to impute missing values. The “m=5” argument specifies that five imputed datasets should be created, and the “seed=123” argument sets a seed for reproducibility. Finally, the “complete” function is used to extract the imputed data from the MICE object.</p>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>To conclude the last part, after imputing the missing values, the model did not become better unfortunately. This shows that it is quite hard to choose a stable method.</p>
<p>Overall, the webshop managers should look more closely at the Time_Products_Average, Review_rating and Ease_of_purchase variables, since the model using only those attributes produced the most accurate outcome.</p>
<p>It is advised for the managers to make sure that the webshop is appealing, inviting and does motivate the customer to send more time on it. Also, it is advised to look into high ratings on review of product and in ease of purchase, since the people with higher scores on those dimensions ended up spending higher amounts on the website.</p>
<p>Finding out why these things happen can help the company generate more revenue, and eventually profit.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>